[providers.age]
type = "age"
recipients = [
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII5i78b9nAGTpA1BZYWaJ5zDNQ5T7a3wM4ziLjq8HUZX",
    "age1dr5u8j2h69adjufg33833rkpqvmst7pethtchjz6j5rwsxq4mqpq3kh8pj",
]

[providers.onepass]
type = "1password"
vault = "Development"

[secrets.TEST]
provider = "age"

[secrets.OP_SERVICE_ACCOUNT_TOKEN]
provider = "age"
value = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IHJWbmh4dyBtRzh1ekM3VnZOVkNXU3lmdjR1QmV6VE5SMnlLazNTTUQrRnRlNjJJVDBrCjRZY2tadnZhNVFiRmVucU9Dc0gvOVlORUlDYjRmUjlpc2k3SThXRGtuckkKLT4gWDI1NTE5IHF6WlhtOW1Belo4SjNDaWJJekJFYWpmUmZWM204T21uSXYxajdsMkQrZ28KamIwRTUzYmozbm1DNVRCdmYrWlFrKzBsZjdGZm9ZK2M3SDdQQnhzQTREUQotLS0gcXZmcDhpcU8rRnNjeUJvUllhMjAwWEYyYXhGWE9sWjB5SC9GbnRqczlSYwoXIJk4/5lKX/XuI5H28VtDEQ7tR767O9Arbn187aEUBC1O5hdmg2PN+if/OIjmRUQQ7ycp5onGXVzIAlZZF0dexdotXezNvMi/tggY1IQnb3eJ8naE65kIunv5sjttjrpfDTaIwrOZAjtThFu4CG3PKmyiEQfvkd+m8Vc7VBtPKILN4qrkEE4RvZApEOcZfdKUBrvw6lcLZ0sRGPtm5FoWLQaqewK0Rq10mLLVlqIkY3BYv9r3PZ27+KYJkE8cOXyxx8FaCz150GReL30SuUCmgYe1J/SZ+oINqr5ime9/rskXvmL/obATpBm+nP77eg7lH07e2l9Ppen8VOOi7x5o8Q8QBbGAzCAcecnuXCaa2KUyYwk0muL+Vwt/U7GiQBJlICfgDJG5BV3h9XhS4T07AF3ttgrBSNJ5j+IYQ2tax4XX8C6lo2Hi4ccVeag6m1bskTT3vyRi/t1pRD33DUrNLhR0n7eudjwF8BE1aqUyevb2YsHYgaap4fifXydAQXLFts/DjdqBZjMSm3BhITTQ0Fu6n6a64lEzjN1eXeX4Xwa4DjJKVMBcxJ/OqgUE1cpZ9Mm1XcI+nyhxp0smAz+mIXITmQz7XhlXj2CPSR7EucGMi7qRH1tm3dJxmkiuHW500uH/YNsqTOFPr8AVoVoUB5gNuG79G7DihqDNgr28Mk/tZ424u+FxMNr9RqilmWz7rE7RJAWOJ8ftHeobDidZno8jedrjzD2nC3bYHyWuUaKhFgmw490Xiu+IhmrfNDAG96GVXn/qTgDckGpzMPm3Er82/6jWzZYXMqeBhmsVvCqjvmLgDDQ0QZX4su8UJIVysGvJehKIUNiPkzxX6b9uZzdPnye/d+yLNAgQyXI1OjlelU1N9QNIRfSL1j4h77tR/kFhcNkL5l14EDEtjrOarT9LPjOEfe/WQRaStLLjL/O1SHS21CehCbfg9VWRwApg1hsbG/8dGCbukn1/eAIJrX465Gg1vo6U8haaB7G3NP/UtRz6OPTFIqdltOr9afy2mL9tWzlRqjfIswL9l4E1PE2b7EgNRDXGfDC4/jHB/Rlz/m0P/WPWKTSz0BcpFNyLK4sv++jvJyg3rv4f0URw2dYHSUNf+KaI/gYyo8ppuspBJyFgbI1qfbgKPwf9buXmM4i/xwTQtOyrXwZWFKD8k3WhkwMuJHi5lMWfOT8="

[secrets.DATABASE_PASSWORD]
provider = "onepass"
value = "Database"
