name: Deploy Telegram Watchdog

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.TGWATCHDOG_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.TGWATCHDOG_VPS_IP }} >> ~/.ssh/known_hosts

      - name: Deploy via SSH
        run: |
          ssh tgwatchdog@${{ secrets.TGWATCHDOG_VPS_IP }} << 'EOF'
            set -e

            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

            cd ~/tgwatchdog
            git pull origin main

            cd backend
            npm install --omit=dev
            pm2 restart backend

            cd ../frontend
            npm install
            npm run build

            rm -rf /var/www/tgwatchdog/*
            cp -r dist/* /var/www/tgwatchdog/
          EOF
