name: Deploy Telegram Watchdog

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.TGWATCHDOG_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.TGWATCHDOG_VPS_IP }} >> ~/.ssh/known_hosts

      - name: Deploy via SSH
        run: |
          ssh tgwatchdog@${{ secrets.TGWATCHDOG_VPS_IP }} << 'EOF'
            set -e

            export OP_SERVICE_ACCOUNT_TOKEN="${{ secrets.OP_SERVICE_ACCOUNT_TOKEN}}"

            cd /ops/tgwatchdog
            git pull --recurse-submodules && git submodule update --init --recursive

            cd backend
            mise install
            eval "$(mise hook-env)"
            fnox export --format env > .env
            npm ci
            npm run stop
            npm run clean
            npm start

            cd ../frontend-vue3
            mise install
            eval "$(mise hook-env)"
            fnox export --format env > .env
            npm ci
            npm run build
            chmod -R 755 ./dist

          EOF
