# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Automaticlly Depoly when main branch updated

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: SSH Command
        # You may pin to the exact commit or the version.
        # uses: D3rHase/ssh-command-action@981832f056c539720824429fa91df009db0ee9cd
        uses: D3rHase/ssh-command-action@v0.2.1
        with:
          # hostname / IP of the server
          HOST: ${{ secrets.REMOTE_HOST }}
          # ssh port of the server
          USER: ${{ secrets.REMOTE_USER }}
          # private ssh key registered on the server
          PRIVATE_SSH_KEY: ${{ SSH_PRIVATE_KEY }
          # command to be executed
          COMMAND: "cd ~/tg-watchdog | git pull | pm2 restart tg-watchdog"
